### ISSUE TITLE
Linux Port?

### ISSUE THREAD

**Issue by skylabhalo** [RayCarrot/RayCarrot.RCP.Metro#6]
Tried running it with wine but it doesn't work for me. Followed a tutorial on reddit :c

**Comment by RayCarrot** [comment]
I'm only on Windows so I don't really know much about that, sorry. Is there a specific error you get or a crashlog? Reg. a native port, that is not something I can do. The framework this runs on is Windows-only.

**Comment by skylabhalo** [comment]
```
0120:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 10003109, 28) stub
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0321060D, 28) stub
0120:fixme:heap:GetNumaHighestNodeNumber semi-stub: 027CFC4C
0120:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 03200000) stub
0120:fixme:nls:LCIDToLocaleName unsupported flags 8000000
0120:fixme:nls:get_dummy_preferred_ui_language (0x8 027CDBB4 00000000 027CDBB0) returning a dummy value (current locale)
0120:fixme:nls:get_dummy_preferred_ui_language (0x8 027CDBB4 028403F0 027CDBB0) returning a dummy value (current locale)
0120:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 03ECFAEC, 64) stub
0120:fixme:bcrypt:BCryptGetFipsAlgorithmMode 027CD864 - semi-stub
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 03F35F40, 51) stub
0084:fixme:imm:ImeSetActiveContext (0x288040, 0): stub
0084:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000288040): stub
0120:fixme:imm:ImeSetActiveContext (0x28928d8, 1): stub
0120:fixme:imm:ImmReleaseContext (00010066, 028928D8): stub
0120:fixme:virtual:NtFlushProcessWriteBuffers stub
0120:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime"): stub
0120:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000402,00000000,0x0001,0x00000000,027CD280,00000000): stub
0120:err:eventlog:ReportEventW L"Application: Rayman Control Panel.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.AccessViolationException\n   at MS.Win32.UnsafeNativeMethods.IntRegisterClassEx(WNDCLASSEX_D)\n   at MS.Win32.UnsafeNativeMe"...
0120:fixme:advapi:DeregisterEventSource (CAFE4242) stub

Unhandled Exception: 0120:fixme:ver:GetCurrentPackageId (027CB9A0 00000000): stub
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is oft
en an indication that other memory is corrupt.
   at MS.Win32.UnsafeNativeMethods.IntRegisterClassEx(WNDCLASSEX_D wc_d)
   at MS.Win32.UnsafeNativeMethods.RegisterClassEx(WNDCLASSEX_D wc_d)
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, 
Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.SystemResources.EnsureResourceChangeListener()
   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, 
Boolean mustReturnDeferredResourceReference)
   at System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, D
ependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boole
an mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Objec
t& source)
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boole
an allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolea
n allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean all
owDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(IList`1 staticResources, IServiceProvider 
serviceProvider, StaticResourceExtension staticResourceWorker)
   at System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   at System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_Deferrabl
eContent>b__297_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object v
alue, Boolean onParent)
   at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, B
oolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlL
ineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, 
Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Obj
ect rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boo
lean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUs
eTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader&
 asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri ba
seUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNav
igation, XamlReader& asyncObjectConverter)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_Source>b_
_342_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object v
alue, Boolean onParent)
   at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, B
oolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlL
ineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, 
Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Obj
ect rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boo
lean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUs
eTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader&
 asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri ba
seUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNav
igation, XamlReader& asyncObjectConverter)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_Source>b_
_342_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.SetValue(Object obj, XamlMember property, Object va
lue)
   at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object v
alue, Boolean onParent)
   at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndMember()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, B
oolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlL
ineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, 
Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Obj
ect rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boo
lean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RayCarrot.RCP.Metro.App.InitializeComponent() in C:\Dev\RayCarrot\RCP_Metro\RayCarrot.RCP.Metro\src\RayC
arrot.RCP.Metro\App.xaml:line 1
   at RayCarrot.RCP.Metro.Entry.Main(String[] args) in C:\Dev\RayCarrot\RCP_Metro\RayCarrot.RCP.Metro\src\RayC
arrot.RCP.Metro\Entry.cs:line 26
wine: Unhandled page fault on write access to 033037C8 at address 7B039626 (thread 0120), starting debugger...
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
Unhandled exception: page fault on write access to 0x033037c8 in 32-bit code (0x7b039626).
0134:fixme:dbghelp:elf_search_auxv can't find symbol in module
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b039626 ESP:027ce4e0 EBP:027ce578 EFLAGS:00010293(  R- --  I S -A- -C)
 EAX:00000000 EBX:033037c8 ECX:033037c9 EDX:00000000
 ESI:00150222 EDI:00000001
Stack dump:
0x027ce4e0:  00000002 027f0000 027ce510 027ce55c
0x027ce4f0:  00000000 00000000 0288f1d8 70bbe423
0x027ce500:  03250b34 00000002 027ce528 00000001
0x027ce510:  00000002 027f0000 027ce578 7bc275ac
0x027ce520:  02895e40 027ce578 027ce5d8 00150222
0x027ce530:  027ce604 00000001 033037c8 00000000
Backtrace:
=>0 0x7b039626 AccessCheckByTypeAndAuditAlarmW+0x38626() in kernelbase (0x027ce578)
  1 0x6ed0a7e1 CharLowerA+0x37b9() in user32 (0x027ce5d8)
  2 0x6ed0b3b2 CharLowerA+0x438a() in user32 (0x027ce838)
  3 0x585c8e42 in windowsbase.ni (+0xe8e42) (0x027ce8dc)
  4 0x5859b95b in windowsbase.ni (+0xbb95b) (0x027ce8ec)
  5 0x5859b6af in windowsbase.ni (+0xbb6af) (0x027ce978)
  6 0x56914eb2 in presentationframework.ni (+0x304eb2) (0x027ce9bc)
  7 0x56914bd3 in presentationframework.ni (+0x304bd3) (0x027cea10)
  8 0x5690b2f8 in presentationframework.ni (+0x2fb2f8) (0x027cea68)
  9 0x5691dd88 in presentationframework.ni (+0x30dd88) (0x027cea98)
  10 0x5691d8ed in presentationframework.ni (+0x30d8ed) (0x027ceac0)
  11 0x5691d7bd in presentationframework.ni (+0x30d7bd) (0x027ceadc)
  12 0x5691d687 in presentationframework.ni (+0x30d687) (0x027ceb04)
  13 0x5691d542 in presentationframework.ni (+0x30d542) (0x027ceb44)
  14 0x569197e7 in presentationframework.ni (+0x3097e7) (0x027ceb6c)
  15 0x569196cc in presentationframework.ni (+0x3096cc) (0x027ceb8c)
  16 0x581426de in system.xaml.ni (+0x726de) (0x027ceb98)
  17 0x58142652 in system.xaml.ni (+0x72652) (0x027cebcc)
  18 0x581422fc in system.xaml.ni (+0x722fc) (0x027cec00)
  19 0x58140f76 in system.xaml.ni (+0x70f76) (0x027cec40)
  20 0x58140743 in system.xaml.ni (+0x70743) (0x027cec68)
  21 0x5813f680 in system.xaml.ni (+0x6f680) (0x027cec78)
  22 0x56906abf in presentationframework.ni (+0x2f6abf) (0x027cece0)
  23 0x56922cfc in presentationframework.ni (+0x312cfc) (0x027ced38)
  24 0x569535b0 in presentationframework.ni (+0x3435b0) (0x027ced5c)
  25 0x569532f4 in presentationframework.ni (+0x3432f4) (0x027cedac)
  26 0x569527d6 in presentationframework.ni (+0x3427d6) (0x027cede8)
  27 0x56999804 in presentationframework.ni (+0x389804) (0x027cee14)
  28 0x5697d679 in presentationframework.ni (+0x36d679) (0x027cee40)
  29 0x5696cbc6 in presentationframework.ni (+0x35cbc6) (0x027ceea0)
  30 0x5696ca1f in presentationframework.ni (+0x35ca1f) (0x027ceec0)
  31 0x581426de in system.xaml.ni (+0x726de) (0x027ceecc)
  32 0x58142652 in system.xaml.ni (+0x72652) (0x027cef00)
  33 0x581422fc in system.xaml.ni (+0x722fc) (0x027cef34)
  34 0x58140f76 in system.xaml.ni (+0x70f76) (0x027cef74)
  35 0x58149477 in system.xaml.ni (+0x79477) (0x027cef84)
  36 0x581407d3 in system.xaml.ni (+0x707d3) (0x027cefac)
  37 0x5813f680 in system.xaml.ni (+0x6f680) (0x027cefbc)
  38 0x56906abf in presentationframework.ni (+0x2f6abf) (0x027cf024)
  39 0x56922cfc in presentationframework.ni (+0x312cfc) (0x027cf07c)
  40 0x569535b0 in presentationframework.ni (+0x3435b0) (0x027cf0a0)
  41 0x569532f4 in presentationframework.ni (+0x3432f4) (0x027cf0f0)
  42 0x569527d6 in presentationframework.ni (+0x3427d6) (0x027cf12c)
  43 0x56999804 in presentationframework.ni (+0x389804) (0x027cf158)
  44 0x5697d679 in presentationframework.ni (+0x36d679) (0x027cf184)
  45 0x5696cbc6 in presentationframework.ni (+0x35cbc6) (0x027cf1e4)
  46 0x5696ca1f in presentationframework.ni (+0x35ca1f) (0x027cf204)
  47 0x581426de in system.xaml.ni (+0x726de) (0x027cf210)
  48 0x58142652 in system.xaml.ni (+0x72652) (0x027cf244)
  49 0x58148afe in system.xaml.ni (+0x78afe) (0x027cf270)
  50 0x581422fc in system.xaml.ni (+0x722fc) (0x027cf2a4)
  51 0x58140f76 in system.xaml.ni (+0x70f76) (0x027cf2e4)
  52 0x58149477 in system.xaml.ni (+0x79477) (0x027cf2f4)
  53 0x581407d3 in system.xaml.ni (+0x707d3) (0x027cf31c)
  54 0x5813f680 in system.xaml.ni (+0x6f680) (0x027cf32c)
  55 0x56906abf in presentationframework.ni (+0x2f6abf) (0x027cf394)
  56 0x56922cfc in presentationframework.ni (+0x312cfc) (0x027cf3ec)
  57 0x569535b0 in presentationframework.ni (+0x3435b0) (0x027cf410)
  58 0x569532b0 in presentationframework.ni (+0x3432b0) (0x027cf460)
  59 0x56953bf6 in presentationframework.ni (+0x343bf6) (0x027cf48c)
  60 0x06aa2c87 (0x027cf49c)
  61 0x06aa141b (0x027cf4a8)
  62 0x0320eaf6 in clr (+0xeaf6) (0x027cf4b4)
  63 0x03211d50 LogHelp_TerminateOnAssert+0x790() in clr (0x027cf508)
  64 0x03217764 LogHelp_TerminateOnAssert+0x61a4() in clr (0x027cf570)
  65 0x032893f0 EntryPoint+0x707f0() in clr (0x027cf69c)
  66 0x03289ad1 EntryPoint+0x70ed1() in clr (0x027cf910)
  67 0x032899b7 EntryPoint+0x70db7() in clr (0x027cfe08)
  68 0x03289c9d EntryPoint+0x7109d() in clr (0x027cfe60)
  69 0x03289be3 EntryPoint+0x70fe3() in clr (0x027cfea0)
  70 0x03259d5c EntryPoint+0x4115c() in clr (0x027cfedc)
  71 0x1000d93b CLRCreateInstance+0x33fb() in mscoreei (0x027cff18)
  72 0x79007f16 EntryPoint+0x50c2() in mscoree (0x027cff28)
  73 0x79004de3 EntryPoint+0x1f8f() in mscoree (0x027cff48)
  74 0x7bc59227 A_SHAFinal+0x39847() in ntdll (0x027cff5c)
  75 0x7bc598e0 A_SHAFinal+0x39f00() in ntdll (0x027cffec)
0x7b039626 kernelbase+0x39626: movb     %al,0xffffffff(%ecx)
Modules:
Module  Address                 Debug info      Name (108 modules)
PE      00400000-025c4000       Deferred        rayman control panel
PE      03200000-038ee000       Export          clr
PE      038f0000-039e5000       Deferred        msvcr120_clr0400
PE      06ab0000-06b30000       Deferred        clrjit
PE      06c50000-07660000       Deferred        system.ni
PE      07660000-0820e000       Deferred        presentationcore.ni
PE      08210000-0948c000       Deferred        magick.native-q8-x86
PE      09490000-09def000       Deferred        shell32
PE      09df0000-09e7e000       Deferred        gdiplus
PE      09e90000-09fd9000       Deferred        wpfgfx_v0400
PE      09fe0000-0a058000       Deferred        msvcp120_clr0400
PE      0a060000-0a12a000       Deferred        presentationnative_v0400
PE      0a1a0000-0a1bf000       Deferred        clrcompression
PE      0a1e0000-0a91e000       Deferred        system.xml.ni
PE      0af40000-0b028000       Deferred        diasymreader
PE      10000000-1007d000       Export          mscoreei
PE      56610000-57917000       Export          presentationframework.ni
PE      580d0000-582c4000       Export          system.xaml.ni
PE      584e0000-588d3000       Export          windowsbase.ni
PE      60370000-6046c000       Deferred        system.configuration.ni
PE      61500000-6152f000       Deferred        iphlpapi
PE      61740000-61783000       Deferred        advapi32
PE      61940000-619cd000       Deferred        wininet
PE      61a00000-621e0000       Deferred        system.core.ni
PE      62d40000-62ee8000       Deferred        windowscodecs
PE      62fc0000-6304e000       Deferred        rpcrt4
PE      63480000-6348c000       Deferred        version
PE      637c0000-63869000       Deferred        urlmon
PE      63bc0000-63bda000       Deferred        shcore
PE      64a40000-64a94000       Deferred        shlwapi
PE      64ec0000-64fed000       Deferred        oleaut32
PE      66240000-66256000       Deferred        bcrypt
PE      66b00000-66b3e000       Deferred        win32u
PE      68500000-6855c000       Deferred        combase
PE      68700000-68730000       Deferred        uxtheme
PE      68e00000-68e11000       Deferred        aclui
PE      69940000-6996b000       Deferred        propsys
PE      6a280000-6a32c000       Deferred        msvcrt
PE      6a400000-6a534000       Deferred        ole32
PE      6bc00000-6bc2c000       Deferred        sechost
PE      6be40000-6bebb000       Deferred        dwrite
PE      6c9c0000-6ca46000       Deferred        gdi32
PE      6cc40000-6cd9c000       Deferred        comctl32
PE      6d780000-6d7a8000       Deferred        ws2_32
PE      6e4c0000-6e4d6000       Deferred        dnsapi
PE      6e8c0000-6e995000       Deferred        crypt32
PE      6ed00000-6ef0d000       Dwarf           user32
PE      6f480000-6f48b000       Deferred        nsi
PE      6fe40000-6fe74000       Deferred        rsaenh
PE      70940000-7095f000       Deferred        mpr
PE      70b40000-70c18000       Deferred        ucrtbase
PE      71200000-7121c000       Deferred        imm32
PE      79000000-7904a000       Export          mscoree
PE      79720000-7aa9e000       Deferred        mscorlib.ni
PE      7b000000-7b0ed000       Dwarf           kernelbase
PE      7b600000-7b81d000       Deferred        kernel32
PE      7bc00000-7bca6000       Dwarf           ntdll
ELF     7d000000-7d005000       Deferred        <wine-loader>
ELF     7d278000-7d3f9000       Deferred        libunistring.so.2
ELF     7d550000-7d556000       Deferred        dwrite.so
ELF     7d558000-7d563000       Deferred        libffi.so.8
ELF     7d568000-7d5f4000       Deferred        libgmp.so.10
ELF     7d5f8000-7d642000       Deferred        libhogweed.so.6
ELF     7d648000-7d692000       Deferred        libnettle.so.8
ELF     7d698000-7d6af000       Deferred        libtasn1.so.6
ELF     7d6b0000-7d6d3000       Deferred        libidn2.so.0
ELF     7d6d8000-7d81d000       Deferred        libp11-kit.so.0
ELF     7d820000-7da4a000       Deferred        libgnutls.so.30
ELF     7da50000-7da63000       Deferred        libresolv.so.2
ELF     7da68000-7da6d000       Deferred        dnsapi.so
ELF     7da70000-7da76000       Deferred        ws2_32.so
ELF     7da78000-7da82000       Deferred        bcrypt.so
ELF     7dbb0000-7dd00000       Deferred        libx11.so.6
ELF     7de08000-7de0f000       Deferred        crypt32.so
ELF     7de38000-7de40000       Deferred        libxfixes.so.3
ELF     7de40000-7de4d000       Deferred        libxcursor.so.1
ELF     7de78000-7de87000       Deferred        libxrandr.so.2
ELF     7de90000-7dea5000       Deferred        libxi.so.6
ELF     7dea8000-7dead000       Deferred        libxcomposite.so.1
ELF     7deb0000-7deb8000       Deferred        libxdmcp.so.6
ELF     7deb8000-7dee4000       Deferred        libxcb.so.1
ELF     7dee8000-7defe000       Deferred        libxext.so.6
ELF     7e008000-7e00d000       Deferred        libxau.so.6
ELF     7e010000-7e015000       Deferred        libdl.so.2
ELF     7e020000-7e02e000       Deferred        libxrender.so.1
ELF     7e030000-7e037000       Deferred        libxxf86vm.so.1
ELF     7e038000-7e03d000       Deferred        libxinerama.so.1
ELF     7e040000-7e0ed000       Deferred        winex11<elf>
  \-PE  7e060000-7e0ed000       \               winex11
ELF     7e2e8000-7e318000       Deferred        libexpat.so.1
ELF     7e318000-7e36b000       Deferred        libfontconfig.so.1
ELF     7e370000-7e375000       Deferred        libpthread.so.0
ELF     7e378000-7e3f3000       Deferred        libpcre.so.1
ELF     7e3f8000-7e41b000       Deferred        libbrotlicommon.so.1
ELF     7e420000-7e572000       Deferred        libglib-2.0.so.0
ELF     7e578000-7e586000       Deferred        libbrotlidec.so.1
ELF     7e588000-7e686000       Deferred        libharfbuzz.so.0
ELF     7e688000-7e6c5000       Deferred        libpng16.so.16
ELF     7e6c8000-7e6da000       Deferred        libbz2.so.1.0
ELF     7e6e0000-7e6fa000       Deferred        libz.so.1
ELF     7e700000-7e7ca000       Deferred        libfreetype.so.6
ELF     7e7d0000-7e7ee000       Deferred        libgcc_s.so.1
ELF     7e7f0000-7e8c1000       Deferred        libm.so.6
ELF     7e8f0000-7e9f3000       Deferred        win32u.so
ELF     7e9f8000-7eb7f000       Dwarf           libwine.so.1
ELF     f7c00000-f7cb9000       Deferred        ntdll.so
ELF     f7cc0000-f7ef0000       Deferred        libc.so.6
ELF     f7f18000-f7f51000       Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
        ["C:\windows\syswow64\start.exe" /exec "Rayman Control Panel.exe"]
        00000024    0
00000038 services.exe
        0000003c    0
        00000040    0
        0000004c    0
        00000050    0
        00000064    0
        00000088    0
        000000b8    0
        000000bc    0
        000000cc    0
        000000e0    0
        000000ec    0
00000044 svchost.exe
        00000048    0
        00000054    0
        00000058    0
0000005c winedevice.exe
        00000060    0
        00000068    0
        0000006c    0
        00000070    0
        00000074    0
        000000d0    0
00000078 winedevice.exe
        0000007c    0
        0000008c    0
        00000090    0
        00000094    0
        00000098    0
        0000009c    0
        000000a0    0
        000000dc    0
        000000f0    0
        0000010c    0
        00000110    0
00000080 explorer.exe
        00000084    0
        000000a4    0
        000000a8    0
000000b0 plugplay.exe
        000000b4    0
        000000c0    0
        000000c4    0
        000000c8    0
        000000d4    0
        000000d8    0
000000e4 rpcss.exe
        000000e8    0
        000000f4    0
        000000f8    0
        000000fc    0
        00000100    0
        00000104    0
        00000108    0
00000114 conhost.exe
        00000118    0
0000011c (D) Z:\home\skylabhalo\Documents\Rayman Control Panel.exe
        ["Z:\home\skylabhalo\Documents\Rayman Control Panel.exe" ]
        00000120    0 <==
        00000124    0
        00000128    2
        0000012c    0
        00000138    0
System information:
    Wine build: wine-7.4 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 5.16.14-zen1-1-zen
```
Here's the console log

**Comment by RayCarrot** [comment]
Hm, there's nothing in there I really recognize sadly enough. Seems the crash is probably UI related since it's in the `LoadBaml` call. I can't really help much more than that though.

**Comment by skylabhalo** [comment]
okay with a clean wine prefix I got it to show the rayman control panel logo but then it crashes with a crashlog I'm gonna attach it
[crashlog.txt](https://github.com/RayCarrot/RayCarrot.RCP.Metro/files/8308785/crashlog.txt)

**Comment by RayCarrot** [comment]
Seems the WPF trace listener is failing now. I'm not sure why though. Do you know .NET Framework version you're using? It should be at least 4.7.2.
